import java.util.Scanner;

public class GuessRandomNumber{
    // SHILPAK MAKODE
    // below is the question
    // lets run the code
     /* The fun and easy project "Guess the Number" is a short Java project 
           that allows the user to guess the number generated by the computer 
           & involves the following steps:
            1. The system generates a random number from a given range, say 1 to 100.
            2. The user is prompted to enter their given number in a displayed dialogue box.
            3. The computer then tells if the entered number matches the guesses number 
                or it is higher/lower than the generated number.
            4. The game continues under the user guessing the number.
            You can also incorporate further details as:
            • Limiting the number of attempts.
            • Adding more rounds.
            • Displaying score.
            • Giving points based on the number of attempts.
        */
        // this is the code
    public static void guessTheRandomNumber (){
        double a = Math.random()*100 ;              //Math.random();
        int b = (int) Math.floor(a);
        // System.out.println(b);                   //To Check I have Add This Line 
        try (Scanner sc = new Scanner (System.in)) {
            System.out.println("You Have to Guess The Number Which is Randomly Generated by the System between 0 to 100:-");
            for (int i = 1; i <= 10; i++){
                    Float c = sc.nextFloat();
                if (c == b) {
                    System.out.println("Congratulation!! Your Guessing is Correct. " + "It tooks you " + i + " attemps.");
                    int s = (100-(5*(i-1)));
                        System.out.println("Your Score is " + s);
                        return;
                } else if (c > b) {
                    System.out.println("Your entered number is greater than randomly generated number!!");
                } else {
                    System.out.println("Your entered number is less than randomly generated number!!");
                }
                if (i == 10 && c != b) {
                    System.out.println("\nYou have reached the MAXIMUM 10 attemps.\n\nThe Number which is randomly generated is " + b + ".");
                }
            }
            System.out.println();
        }
        // actually i have create a function called guessTheRandomNumber
        // and call it as per requirements!
    }
    public static void main (String args[]) {
        guessTheRandomNumber();
    }
}